// <auto-generated />
using DartsAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DartsAPI.Data.Migrations
{
    [DbContext(typeof(PlayerContext))]
    [Migration("20250219110902_SeedPlayers")]
    partial class SeedPlayers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("DartsAPI.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Alex",
                            Password = "asd"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Marci",
                            Password = "asd"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ármin",
                            Password = "asd"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Kero",
                            Password = "asd"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
