// <auto-generated />
using DartsAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DartsAPI.Data.Migrations
{
    [DbContext(typeof(PlayerContext))]
    partial class PlayerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("DartsAPI.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "asd",
                            Username = "Tesz1"
                        },
                        new
                        {
                            Id = 2,
                            Password = "asd",
                            Username = "Tesz2"
                        },
                        new
                        {
                            Id = 3,
                            Password = "asd",
                            Username = "Teszt3"
                        },
                        new
                        {
                            Id = 4,
                            Password = "asd",
                            Username = "Teszt4"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
